### PR TITLE
Add a resolveBin.sync method using find-parent-dir's sync

### LINKED ISSUE #4: Sync version
It would be awesome of one could do `resolveBin.sync('test')` :+1: 

Awesome lib btw :raised_hands:

### PR DESCRIPTION
**Pull request by bendrucker**
Closes #4

### CODE REVIEW

**Comment by thlorenz** [comment]
LGTM added you as collab on github and npm.
Please merge and publish a new minor.

Thanks.

... looks like adding as npm collab currently failing with a 504.
Gonna have to wait with that one :(

**Comment by bendrucker** [comment]
:+1: Ready for npm publish

**Comment by LinusU** [comment]
Should probably add documentation to the readme as well?

**Comment by thlorenz** [comment]
@LinusU good point ...
@bendrucker added you as collab on npm so you can publish now, but maybe add the doc first?

Thanks

**Pull request merged**
